function fig01_b(ax, options)
axes(ax);
im = imread('environment.png');
imshow(im);

text(.82, .92, "Water", "Units", "normalized", 'Color', ...
    [6 157 255]/255, 'FontSize', options.LabelSize, ...
    "FontName", options.FontName, 'FontWeight', options.FontWeight);

text(.71, 1, "Food", "Units", "normalized", 'Color', ...
   [51 204 51]/255, 'FontSize', options.LabelSize, ...
    "FontName", options.FontName, 'FontWeight', options.FontWeight);