function ax = fig06_task_schematic(pos, options)
% JN 2026-08-05
% Panel A of figure 6: explanation of the number-guessing task.


ax = axes('Position', pos);

ax.Visible = 'off';
ax.XLim = [0, 100];
ax.YLim = [0, 100];
hold(ax,'on');

%% Settings
blue = [0.05 0.05 0.75];
black = [0 0 0];

fontName = 'Arial';

guess = 39;
minVal = 1;
maxVal = 100;

newMax = guess - 1;   % 38

%% Title
text(ax,0,96,'Guess the number', ...
    'FontName',fontName, ...
    'FontSize',17, ...
    'FontWeight','bold', ...
    'Color',blue, ...
    'VerticalAlignment','top');

%% Your guess
text(ax,0,79,'Your guess:', ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'Color',blue, ...
    'VerticalAlignment','middle');

text(ax,42,79,num2str(guess), ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Color',blue, ...
    'VerticalAlignment','middle');

%% First number line
x1 = 10;
x2 = 96;
y1 = 60;

line(ax,[x1 x2],[y1 y1], ...
    'Color',black, ...
    'LineWidth',2);

% End points
plot(ax,x1,y1,'o', ...
    'MarkerSize',5, ...
    'MarkerFaceColor',black, ...
    'MarkerEdgeColor',black);

plot(ax,x2,y1,'o', ...
    'MarkerSize',5, ...
    'MarkerFaceColor',black, ...
    'MarkerEdgeColor',black);

% Endpoint labels
text(ax,x1,y1+6,num2str(minVal), ...
    'HorizontalAlignment','center', ...
    'FontName',fontName, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',black);

text(ax,x2,y1+6,num2str(maxVal), ...
    'HorizontalAlignment','center', ...
    'FontName',fontName, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',black);

%% Guess marker
% Map the guessed number onto the number line
xGuess = x1 + ...
    (guess-minVal)/(maxVal-minVal) * (x2-x1);

plot(ax,xGuess,y1,'o', ...
    'MarkerSize',10, ...
    'MarkerFaceColor',blue, ...
    'MarkerEdgeColor',blue);

%% Feedback
text(ax,1.5,48,'Too high!', ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'Color',blue, ...
    'VerticalAlignment','middle');

text(ax,1.5,35,'Guess again, new range:', ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'Color',blue, ...
    'VerticalAlignment','middle');

%% New range
x3 = 10;
x4 = 45;
y2 = 13;

line(ax,[x3 x4],[y2 y2], ...
    'Color',black, ...
    'LineWidth',2);

plot(ax,x3,y2,'o', ...
    'MarkerSize',5, ...
    'MarkerFaceColor',black, ...
    'MarkerEdgeColor',black);

plot(ax,x4,y2,'o', ...
    'MarkerSize',5, ...
    'MarkerFaceColor',black, ...
    'MarkerEdgeColor',black);

text(ax,x3,y2+6,num2str(minVal), ...
    'HorizontalAlignment','center', ...
    'FontName',fontName, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',black);

text(ax,x4,y2+6,num2str(newMax), ...
    'HorizontalAlignment','center', ...
    'FontName',fontName, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',black);

hold(ax,'off');